version: '2.4'
services:
  locate_object:
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: "host"
    runtime: "nvidia"
    volumes:
      - ./src/locate_object:/canister/src/locate_object
      - ./src/utility:/canister/src/utility
      - ./src/verefine:/canister/src/verefine
      - ./data:/canister/data
      - ./launch:/canister/launch
      - ./config:/canister/config
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - ROS_MASTER_URI
      - ROS_HOSTNAME
      - ROS_IP
    privileged: true
    stdin_open: true
    tty: true
