debug_visualization: True
publish_tf: True
use_refinement: True
use_verefine: True
max_dist: 1.0  # crop points farther than this [meters]
down_scale: 1  # down_scale speeds things up by already subsampling the image [power of 2]

# Camera topics and frames
color_topic: "/camera/color/image_raw"
depth_topic: "/camera/aligned_depth_to_color/image_raw"
camera_info_topic: "/camera/color/camera_info"

# Plane detection
distance_threshold: 0.01
to_meters: 0.001

# Region of Interest
use_roi: true
roi_center: [0.0, 0.0, 1.0]
roi_rotation: [1., 0., 0., 0., 1., 0., 0., 0., 1.]
roi_extent: [2.0, 2.0, 2.0]
