version: '2.4'
services:

  detect:
    image: "maskrcnn"
    network_mode: "host"
    runtime: "nvidia"
    build: 
      context: ../../
      dockerfile: src/maskrcnn/Dockerfile
    volumes:
      - ../../:/hsr-grasping
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      # ROS_MASTER_URI:     # empty value means use same as host
      ROS_MASTER_URI: "http://hsrb:11311"
    
    command: bash -c "source /maskrcnn/catkin_ws/devel/setup.bash; 
                      rosparam load  /config/params.yaml /hsr_grasping;
                      ROS_NAMESPACE=hsr_grasping python3 /maskrcnn/src/maskrcnn/ros_detection.py"
    stdin_open: true
    tty: true

  # run seperate densefusion containers for estimation and refinement or run both in the same container ?

  estimate_refine_ppf:
    image: "ppf"
    network_mode: "host"
    build: 
      context: ../../
      dockerfile: src/ppf/Dockerfile
    runtime: "nvidia"
    volumes:
      - ../../data:/verefine/data
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"   
      ROS_IP: "10.0.0.206"

    entrypoint: ""
    command: bash -c "source /ppf/catkin_ws/devel/setup.bash; 
                      export PYTHONPATH=/ppf/catkin_ws/devel/lib/python3/dist-packages:$$PYTHONPATH; 
                      rosparam load -v /ppf/config/params.yaml /locateobject;
                      rosparam load  /config/params.yaml /hsr_grasping;
                      ROS_NAMESPACE=hsr_grasping python3 /ppf/src/locate_object/ros_locate_object.py"
    stdin_open: true
    tty: true

  grasp:
    image: "hsr-grasping"
    network_mode: "host"
    build: 
      context: ../../
      dockerfile: src/task/Dockerfile
    runtime: "nvidia"
    volumes:
    - ../../lm:/task/lm
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"
      ROS_IP: "10.0.0.206"
      DISPLAY: ${DISPLAY}
      Xvfb: 99 -screen 0 1920x1080x24
      QT_X11_NO_MITSHM: 1 

    command: bash -c "source /task/catkin_ws/devel/setup.bash; 
                      rosparam load  /config/params.yaml /hsr_grasping;
                      ROS_NAMESPACE=hsr_grasping python /task/src/ros_grasp_object.py"

    stdin_open: true
    tty: true
