# Camera topics and frames
im_width: 640
im_height: 480
intrinsics:
- [538.391033533567, 0.0, 315.3074696331638]
- [0.0, 538.085452058436, 233.0483557773859]
- [0.0, 0.0, 1.0]

# Model Directories of container
cfg_dir: "/verefine/data"
models_dir: "/verefine/data/models/renderer"

# YCBV Config Files
ycbv_names: /verefine/data/ycbv_names.json
ycbv_verefine: /verefine/data/ycbv_verefine.json

# Topics
RGB_TOPIC: /hsrb/head_rgbd_sensor/rgb/image_rect_color
DEPTH_TOPIC: /hsrb/head_rgbd_sensor/depth_registered/image_rect_raw
CAMERA_INFO: /hsrb/head_rgbd_sensor/rgb/camera_info
