version: '2.4'
services:

  # run object detection

  detect:
    image: "maskrcnn"
    network_mode: "host"
    runtime: "nvidia"
    build: 
      context: ../../
      dockerfile: src/maskrcnn/Dockerfile
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"
      ROS_IP: "10.0.0.182"
    
    command: bash -c "source /maskrcnn/catkin_ws/devel/setup.bash; 
                      rosparam load  /config/params.yaml /pose_estimator;
                      ROS_NAMESPACE=pose_estimator python3 /maskrcnn/src/maskrcnn/ros_detection.py"
    stdin_open: true
    tty: true

  # run densefusion for estimation and verefine for refinement

  estimate_refine:
    image: "densefusion_verefine"
    network_mode: "host"
    build: 
      context: ../../
      dockerfile: src/verefine/Dockerfile
    runtime: "nvidia"
    volumes:
      - ../../data:/verefine/data
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"   
      ROS_IP: "10.0.0.182"

    entrypoint: ""
    command: bash -c "source /verefine/catkin_ws/devel/setup.bash;
                      rosparam load  /config/params.yaml /pose_estimator;
                      ROS_NAMESPACE=pose_estimator python3 /verefine/src/ros_estimate_poses.py"
    stdin_open: true
    tty: true

  pose:
    image: "pose_estimator"
    network_mode: "host"
    build: 
      context: ../../
      dockerfile: src/task/Dockerfile
    runtime: "nvidia"
    extra_hosts:
      - "hsrb:10.0.0.143"
    environment:
      ROS_MASTER_URI: "http://hsrb:11311"
      ROS_IP: "10.0.0.182"
      DISPLAY: ${DISPLAY}
      Xvfb: 99 -screen 0 1920x1080x24
      QT_X11_NO_MITSHM: 1 

    command: bash -c "source /task/catkin_ws/devel/setup.bash; 
                      rosparam load  /config/params.yaml /pose_estimator;
                      ROS_NAMESPACE=pose_estimator python /task/src/ros_grasp_object.py"

    stdin_open: true
    tty: true
